{{- range $name, $secret := .Values.genericExternalSecrets }}
{{- if $secret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $name }}
spec:
  secretStoreRef:
    kind: {{ $secret.secretStoreRefKind | default "SecretStore" }}
    name: {{ $secret.secretStoreRefName | default "fleet-secret-store" }}
  refreshInterval: {{ $secret.refreshInterval | default "1h" | quote }}
  target:
    name: {{ $secret.targetSecretName }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ (index $secret.dataFrom 0).extract.key }}
        conversionStrategy: {{ default "Default" $secret.conversionStrategy }}
        metadataPolicy: {{ default "None" $secret.metadataPolicy }}
        decodingStrategy: Auto
---
{{- end }}
{{- end }}
