{{- if .Values.secretStore.enabled }}
apiVersion: external-secrets.io/v1
kind: {{ .Values.secretStore.kind }}
metadata:
  name:  {{ .Values.secretStore.name }}
spec:
  provider:
    {{- if eq (default "aws" .Values.secretStore.provider) "aws" }}
    aws:
      service: SecretsManager
      {{- if .Values.secretStore.role }}
      role: {{ .Values.secretStore.role }}
      {{- end }}
      region: {{ .Values.secretStore.region }}
      secretsManager:
        forceDeleteWithoutRecovery: true
    {{- else if eq .Values.secretStore.provider "gcpsm" }}
    gcpsm:
      projectID: {{ required "secretStore.projectID is required for gcpsm provider" .Values.secretStore.projectID }}
      {{- if .Values.secretStore.serviceAccountRef }}
      auth:
        workloadIdentity:
          clusterLocation: {{ .Values.secretStore.clusterLocation }}
          clusterName: {{ .Values.secretStore.clusterName }}
          serviceAccountRef:
            name: {{ .Values.secretStore.serviceAccountRef }}
      {{- end }}
    {{- end }}
{{- end }}