apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: team2-apps
  namespace: gitops-agent-spoke-2
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: 'https://github.com/harness-landing-zone/harness-kube-management'
        revision: main
        directories:
          - path: 'gitops-apps/Team2/*'
  template:
    metadata:
      name: 'team2-{{.path.basename}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/harness-landing-zone/harness-kube-management'
        targetRevision: main
        path: '{{.path.path}}'
      destination:
        server: 'https://192.168.147.2:6443'
        namespace: '{{.path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
